/*
  Warnings:

  - The values [ONLINE_INQUIRY,OFFICE_VISIT,ACADEMIC_DOCS_SUBMITTED,APPLICATION_PROCESSED,APPLICATION_SUBMITTED_TO_UNIVERSITY,UNIVERSITY_ACCEPTANCE_RECEIVED,PAYMENT_DONE,VISA_DOCS_PREPARED,FORWARDED_TO_COMPLIANCE,VISA_DECISION,REFUND_PROCESSED,POST_COUNSELLING_DONE] on the enum `timeline_event` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "timeline_event_new" AS ENUM ('LEAD_CREATED', 'LEAD_NAME_CHANGED', 'LEAD_PHONE_CHANGED', 'LEAD_EMAIL_CHANGED', 'LEAD_PURPOSE_CHANGED', 'LEAD_OWNER_CHANGED', 'LEAD_STATUS_CHANGED', 'LEAD_NOTE_ADDED', 'LEAD_NOTE_DELETED', 'LEAD_NOTE_UPDATED', 'LEAD_FOLLOWUP_ADDED', 'LEAD_FOLLOWUP_DELETED', 'LEAD_FOLLOWUP_UPDATED', 'LEAD_FOLLOWUP_DATE_EXTENDED', 'LEAD_FOLLOWUP_COMPLETED', 'LEAD_FOLLOWUP_COMMENT_ADDED', 'LEAD_FOLLOWUP_COMMENT_DELETED', 'LEAD_FOLLOWUP_COMMENT_UPDATED', 'OFFLINE_PAYMENT_ADDED', 'OFFLINE_PAYMENT_DELETED', 'ONLINE_PAYMENT_INITIATED', 'ONLINE_PAYMENT_VERIFIED', 'ONLINE_PAYMENT_FAILED', 'ONLINE_PAYMENT_CANCELED', 'LEAD_DEPARTMENT_CHANGED');
ALTER TABLE "timeline" ALTER COLUMN "event_type" TYPE "timeline_event_new" USING ("event_type"::text::"timeline_event_new");
ALTER TYPE "timeline_event" RENAME TO "timeline_event_old";
ALTER TYPE "timeline_event_new" RENAME TO "timeline_event";
DROP TYPE "public"."timeline_event_old";
COMMIT;

-- DropEnum
DROP TYPE "StageStatus";
